name: temporal-ui
version: '2.49.1'
summary: Temporal UI 
description: |
  Temporal UI as a snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  temporal-ui:
    daemon: simple
    command: bin/run-temporal-ui
    plugs: [home, network, network-bind]

parts:
  temporal:
    plugin: nil
    source: https://github.com/temporalio/ui-server/releases/download/v2.49.1/ui-server_2.49.1_linux_amd64.tar.gz
    source-checksum: sha256/0d894ac2369252be0eb4569e3a9d28f3c6b044e44436c4da68d7f4f9c708343e
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv ui-server $CRAFT_PART_INSTALL/bin
    stage:
      - bin/ui-server
    prime:
      - bin/ui-server
  tree:
    plugin: dump
    source: snap/local/tree
