name: temporal-ui
version: '2.54.0'
summary: Temporal UI 
description: |
  Temporal UI as a snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  temporal-ui:
    daemon: simple
    command: bin/run-temporal-ui
    plugs: [home, network, network-bind]

parts:
  temporal:
    plugin: nil
    source: https://github.com/temporalio/ui-server/releases/download/v2.54.0/ui-server_2.54.0_linux_amd64.tar.gz
    source-checksum: sha256/3a5878732288be9e06079d17e5a56bbbb8f9d427b509401f2014ee20fcd5acf9
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv ui-server $CRAFT_PART_INSTALL/bin
    stage:
      - bin/ui-server
    prime:
      - bin/ui-server
  tree:
    plugin: dump
    source: snap/local/tree
