name: temporal-ui
version: '2.36.0'
summary: Temporal UI 
description: |
  Temporal UI as a snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  temporal-ui:
    daemon: simple
    command: bin/run-temporal-ui
    plugs: [home, network, network-bind]

parts:
  temporal:
    plugin: nil
    source: https://github.com/temporalio/ui-server/releases/download/v2.36.0/ui-server_2.36.0_linux_amd64.tar.gz 
    source-checksum: sha256/ee34696faf802d40cf64cf5715454931057a9a2b40e12e3165c43f946c2dc912
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv ui-server $CRAFT_PART_INSTALL/bin
    stage:
      - bin/ui-server
    prime:
      - bin/ui-server
  tree:
    plugin: dump
    source: snap/local/tree
